/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonasRouteImport } from './routes/zonas'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RepartidoresRouteImport } from './routes/repartidores'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as MisPedidosRouteImport } from './routes/mis-pedidos'
import { Route as MisEntregasRouteImport } from './routes/mis-entregas'
import { Route as MiRestauranteRouteImport } from './routes/mi-restaurante'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CuponesRouteImport } from './routes/cupones'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantesIndexRouteImport } from './routes/restaurantes.index'
import { Route as RestaurantesIdRouteImport } from './routes/restaurantes.$id'
import { Route as MiRestaurantePedidosRouteImport } from './routes/mi-restaurante.pedidos'

const ZonasRoute = ZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidoresRoute = RepartidoresRouteImport.update({
  id: '/repartidores',
  path: '/repartidores',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPedidosRoute = MisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MisEntregasRoute = MisEntregasRouteImport.update({
  id: '/mis-entregas',
  path: '/mis-entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const MiRestauranteRoute = MiRestauranteRouteImport.update({
  id: '/mi-restaurante',
  path: '/mi-restaurante',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponesRoute = CuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIndexRoute = RestaurantesIndexRouteImport.update({
  id: '/restaurantes/',
  path: '/restaurantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIdRoute = RestaurantesIdRouteImport.update({
  id: '/restaurantes/$id',
  path: '/restaurantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MiRestaurantePedidosRoute = MiRestaurantePedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MiRestauranteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cupones': typeof CuponesRoute
  '/login': typeof LoginRoute
  '/mi-restaurante': typeof MiRestauranteRouteWithChildren
  '/mis-entregas': typeof MisEntregasRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pedidos': typeof PedidosRoute
  '/rankings': typeof RankingsRoute
  '/repartidores': typeof RepartidoresRoute
  '/reportes': typeof ReportesRoute
  '/zonas': typeof ZonasRoute
  '/mi-restaurante/pedidos': typeof MiRestaurantePedidosRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/restaurantes/': typeof RestaurantesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cupones': typeof CuponesRoute
  '/login': typeof LoginRoute
  '/mi-restaurante': typeof MiRestauranteRouteWithChildren
  '/mis-entregas': typeof MisEntregasRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pedidos': typeof PedidosRoute
  '/rankings': typeof RankingsRoute
  '/repartidores': typeof RepartidoresRoute
  '/reportes': typeof ReportesRoute
  '/zonas': typeof ZonasRoute
  '/mi-restaurante/pedidos': typeof MiRestaurantePedidosRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/restaurantes': typeof RestaurantesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/cupones': typeof CuponesRoute
  '/login': typeof LoginRoute
  '/mi-restaurante': typeof MiRestauranteRouteWithChildren
  '/mis-entregas': typeof MisEntregasRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pedidos': typeof PedidosRoute
  '/rankings': typeof RankingsRoute
  '/repartidores': typeof RepartidoresRoute
  '/reportes': typeof ReportesRoute
  '/zonas': typeof ZonasRoute
  '/mi-restaurante/pedidos': typeof MiRestaurantePedidosRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/restaurantes/': typeof RestaurantesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/cupones'
    | '/login'
    | '/mi-restaurante'
    | '/mis-entregas'
    | '/mis-pedidos'
    | '/notificaciones'
    | '/pedidos'
    | '/rankings'
    | '/repartidores'
    | '/reportes'
    | '/zonas'
    | '/mi-restaurante/pedidos'
    | '/restaurantes/$id'
    | '/restaurantes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/cupones'
    | '/login'
    | '/mi-restaurante'
    | '/mis-entregas'
    | '/mis-pedidos'
    | '/notificaciones'
    | '/pedidos'
    | '/rankings'
    | '/repartidores'
    | '/reportes'
    | '/zonas'
    | '/mi-restaurante/pedidos'
    | '/restaurantes/$id'
    | '/restaurantes'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/cupones'
    | '/login'
    | '/mi-restaurante'
    | '/mis-entregas'
    | '/mis-pedidos'
    | '/notificaciones'
    | '/pedidos'
    | '/rankings'
    | '/repartidores'
    | '/reportes'
    | '/zonas'
    | '/mi-restaurante/pedidos'
    | '/restaurantes/$id'
    | '/restaurantes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  CuponesRoute: typeof CuponesRoute
  LoginRoute: typeof LoginRoute
  MiRestauranteRoute: typeof MiRestauranteRouteWithChildren
  MisEntregasRoute: typeof MisEntregasRoute
  MisPedidosRoute: typeof MisPedidosRoute
  NotificacionesRoute: typeof NotificacionesRoute
  PedidosRoute: typeof PedidosRoute
  RankingsRoute: typeof RankingsRoute
  RepartidoresRoute: typeof RepartidoresRoute
  ReportesRoute: typeof ReportesRoute
  ZonasRoute: typeof ZonasRoute
  RestaurantesIdRoute: typeof RestaurantesIdRoute
  RestaurantesIndexRoute: typeof RestaurantesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zonas': {
      id: '/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof ZonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidores': {
      id: '/repartidores'
      path: '/repartidores'
      fullPath: '/repartidores'
      preLoaderRoute: typeof RepartidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pedidos': {
      id: '/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof MisPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-entregas': {
      id: '/mis-entregas'
      path: '/mis-entregas'
      fullPath: '/mis-entregas'
      preLoaderRoute: typeof MisEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-restaurante': {
      id: '/mi-restaurante'
      path: '/mi-restaurante'
      fullPath: '/mi-restaurante'
      preLoaderRoute: typeof MiRestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupones': {
      id: '/cupones'
      path: '/cupones'
      fullPath: '/cupones'
      preLoaderRoute: typeof CuponesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/': {
      id: '/restaurantes/'
      path: '/restaurantes'
      fullPath: '/restaurantes/'
      preLoaderRoute: typeof RestaurantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/$id': {
      id: '/restaurantes/$id'
      path: '/restaurantes/$id'
      fullPath: '/restaurantes/$id'
      preLoaderRoute: typeof RestaurantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-restaurante/pedidos': {
      id: '/mi-restaurante/pedidos'
      path: '/pedidos'
      fullPath: '/mi-restaurante/pedidos'
      preLoaderRoute: typeof MiRestaurantePedidosRouteImport
      parentRoute: typeof MiRestauranteRoute
    }
  }
}

interface MiRestauranteRouteChildren {
  MiRestaurantePedidosRoute: typeof MiRestaurantePedidosRoute
}

const MiRestauranteRouteChildren: MiRestauranteRouteChildren = {
  MiRestaurantePedidosRoute: MiRestaurantePedidosRoute,
}

const MiRestauranteRouteWithChildren = MiRestauranteRoute._addFileChildren(
  MiRestauranteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  CuponesRoute: CuponesRoute,
  LoginRoute: LoginRoute,
  MiRestauranteRoute: MiRestauranteRouteWithChildren,
  MisEntregasRoute: MisEntregasRoute,
  MisPedidosRoute: MisPedidosRoute,
  NotificacionesRoute: NotificacionesRoute,
  PedidosRoute: PedidosRoute,
  RankingsRoute: RankingsRoute,
  RepartidoresRoute: RepartidoresRoute,
  ReportesRoute: ReportesRoute,
  ZonasRoute: ZonasRoute,
  RestaurantesIdRoute: RestaurantesIdRoute,
  RestaurantesIndexRoute: RestaurantesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
