/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonasRouteImport } from './routes/zonas'
import { Route as RestauranteDashboardRouteImport } from './routes/restaurante-dashboard'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RepartidoresRouteImport } from './routes/repartidores'
import { Route as RepartidorDashboardRouteImport } from './routes/repartidor-dashboard'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as NuevoPedidoRouteImport } from './routes/nuevo-pedido'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as MisPedidosRouteImport } from './routes/mis-pedidos'
import { Route as MisEntregasRouteImport } from './routes/mis-entregas'
import { Route as MiRestauranteRouteImport } from './routes/mi-restaurante'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CuponesRouteImport } from './routes/cupones'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ClienteDashboardRouteImport } from './routes/cliente-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantesIndexRouteImport } from './routes/restaurantes.index'
import { Route as RestaurantesIdRouteImport } from './routes/restaurantes.$id'
import { Route as RepartidoresIdRouteImport } from './routes/repartidores.$id'
import { Route as MiRestaurantePedidosRouteImport } from './routes/mi-restaurante.pedidos'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as RestaurantesIdPanelRouteImport } from './routes/restaurantes.$id.panel'

const ZonasRoute = ZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranteDashboardRoute = RestauranteDashboardRouteImport.update({
  id: '/restaurante-dashboard',
  path: '/restaurante-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidoresRoute = RepartidoresRouteImport.update({
  id: '/repartidores',
  path: '/repartidores',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidorDashboardRoute = RepartidorDashboardRouteImport.update({
  id: '/repartidor-dashboard',
  path: '/repartidor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoPedidoRoute = NuevoPedidoRouteImport.update({
  id: '/nuevo-pedido',
  path: '/nuevo-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPedidosRoute = MisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MisEntregasRoute = MisEntregasRouteImport.update({
  id: '/mis-entregas',
  path: '/mis-entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const MiRestauranteRoute = MiRestauranteRouteImport.update({
  id: '/mi-restaurante',
  path: '/mi-restaurante',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponesRoute = CuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/cliente-dashboard',
  path: '/cliente-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIndexRoute = RestaurantesIndexRouteImport.update({
  id: '/restaurantes/',
  path: '/restaurantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIdRoute = RestaurantesIdRouteImport.update({
  id: '/restaurantes/$id',
  path: '/restaurantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidoresIdRoute = RepartidoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepartidoresRoute,
} as any)
const MiRestaurantePedidosRoute = MiRestaurantePedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MiRestauranteRoute,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const RestaurantesIdPanelRoute = RestaurantesIdPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => RestaurantesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente-dashboard': typeof ClienteDashboardRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cupones': typeof CuponesRoute
  '/login': typeof LoginRoute
  '/mi-restaurante': typeof MiRestauranteRouteWithChildren
  '/mis-entregas': typeof MisEntregasRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/nuevo-pedido': typeof NuevoPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/rankings': typeof RankingsRoute
  '/repartidor-dashboard': typeof RepartidorDashboardRoute
  '/repartidores': typeof RepartidoresRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/restaurante-dashboard': typeof RestauranteDashboardRoute
  '/zonas': typeof ZonasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/mi-restaurante/pedidos': typeof MiRestaurantePedidosRoute
  '/repartidores/$id': typeof RepartidoresIdRoute
  '/restaurantes/$id': typeof RestaurantesIdRouteWithChildren
  '/restaurantes/': typeof RestaurantesIndexRoute
  '/restaurantes/$id/panel': typeof RestaurantesIdPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente-dashboard': typeof ClienteDashboardRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cupones': typeof CuponesRoute
  '/login': typeof LoginRoute
  '/mi-restaurante': typeof MiRestauranteRouteWithChildren
  '/mis-entregas': typeof MisEntregasRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/nuevo-pedido': typeof NuevoPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/rankings': typeof RankingsRoute
  '/repartidor-dashboard': typeof RepartidorDashboardRoute
  '/repartidores': typeof RepartidoresRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/restaurante-dashboard': typeof RestauranteDashboardRoute
  '/zonas': typeof ZonasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/mi-restaurante/pedidos': typeof MiRestaurantePedidosRoute
  '/repartidores/$id': typeof RepartidoresIdRoute
  '/restaurantes/$id': typeof RestaurantesIdRouteWithChildren
  '/restaurantes': typeof RestaurantesIndexRoute
  '/restaurantes/$id/panel': typeof RestaurantesIdPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente-dashboard': typeof ClienteDashboardRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cupones': typeof CuponesRoute
  '/login': typeof LoginRoute
  '/mi-restaurante': typeof MiRestauranteRouteWithChildren
  '/mis-entregas': typeof MisEntregasRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/nuevo-pedido': typeof NuevoPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/rankings': typeof RankingsRoute
  '/repartidor-dashboard': typeof RepartidorDashboardRoute
  '/repartidores': typeof RepartidoresRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/restaurante-dashboard': typeof RestauranteDashboardRoute
  '/zonas': typeof ZonasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/mi-restaurante/pedidos': typeof MiRestaurantePedidosRoute
  '/repartidores/$id': typeof RepartidoresIdRoute
  '/restaurantes/$id': typeof RestaurantesIdRouteWithChildren
  '/restaurantes/': typeof RestaurantesIndexRoute
  '/restaurantes/$id/panel': typeof RestaurantesIdPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente-dashboard'
    | '/clientes'
    | '/cupones'
    | '/login'
    | '/mi-restaurante'
    | '/mis-entregas'
    | '/mis-pedidos'
    | '/notificaciones'
    | '/nuevo-pedido'
    | '/pedidos'
    | '/rankings'
    | '/repartidor-dashboard'
    | '/repartidores'
    | '/reportes'
    | '/restaurante-dashboard'
    | '/zonas'
    | '/clientes/$id'
    | '/mi-restaurante/pedidos'
    | '/repartidores/$id'
    | '/restaurantes/$id'
    | '/restaurantes/'
    | '/restaurantes/$id/panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente-dashboard'
    | '/clientes'
    | '/cupones'
    | '/login'
    | '/mi-restaurante'
    | '/mis-entregas'
    | '/mis-pedidos'
    | '/notificaciones'
    | '/nuevo-pedido'
    | '/pedidos'
    | '/rankings'
    | '/repartidor-dashboard'
    | '/repartidores'
    | '/reportes'
    | '/restaurante-dashboard'
    | '/zonas'
    | '/clientes/$id'
    | '/mi-restaurante/pedidos'
    | '/repartidores/$id'
    | '/restaurantes/$id'
    | '/restaurantes'
    | '/restaurantes/$id/panel'
  id:
    | '__root__'
    | '/'
    | '/cliente-dashboard'
    | '/clientes'
    | '/cupones'
    | '/login'
    | '/mi-restaurante'
    | '/mis-entregas'
    | '/mis-pedidos'
    | '/notificaciones'
    | '/nuevo-pedido'
    | '/pedidos'
    | '/rankings'
    | '/repartidor-dashboard'
    | '/repartidores'
    | '/reportes'
    | '/restaurante-dashboard'
    | '/zonas'
    | '/clientes/$id'
    | '/mi-restaurante/pedidos'
    | '/repartidores/$id'
    | '/restaurantes/$id'
    | '/restaurantes/'
    | '/restaurantes/$id/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteDashboardRoute: typeof ClienteDashboardRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  CuponesRoute: typeof CuponesRoute
  LoginRoute: typeof LoginRoute
  MiRestauranteRoute: typeof MiRestauranteRouteWithChildren
  MisEntregasRoute: typeof MisEntregasRoute
  MisPedidosRoute: typeof MisPedidosRoute
  NotificacionesRoute: typeof NotificacionesRoute
  NuevoPedidoRoute: typeof NuevoPedidoRoute
  PedidosRoute: typeof PedidosRoute
  RankingsRoute: typeof RankingsRoute
  RepartidorDashboardRoute: typeof RepartidorDashboardRoute
  RepartidoresRoute: typeof RepartidoresRouteWithChildren
  ReportesRoute: typeof ReportesRoute
  RestauranteDashboardRoute: typeof RestauranteDashboardRoute
  ZonasRoute: typeof ZonasRoute
  RestaurantesIdRoute: typeof RestaurantesIdRouteWithChildren
  RestaurantesIndexRoute: typeof RestaurantesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zonas': {
      id: '/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof ZonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurante-dashboard': {
      id: '/restaurante-dashboard'
      path: '/restaurante-dashboard'
      fullPath: '/restaurante-dashboard'
      preLoaderRoute: typeof RestauranteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidores': {
      id: '/repartidores'
      path: '/repartidores'
      fullPath: '/repartidores'
      preLoaderRoute: typeof RepartidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidor-dashboard': {
      id: '/repartidor-dashboard'
      path: '/repartidor-dashboard'
      fullPath: '/repartidor-dashboard'
      preLoaderRoute: typeof RepartidorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo-pedido': {
      id: '/nuevo-pedido'
      path: '/nuevo-pedido'
      fullPath: '/nuevo-pedido'
      preLoaderRoute: typeof NuevoPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pedidos': {
      id: '/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof MisPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-entregas': {
      id: '/mis-entregas'
      path: '/mis-entregas'
      fullPath: '/mis-entregas'
      preLoaderRoute: typeof MisEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-restaurante': {
      id: '/mi-restaurante'
      path: '/mi-restaurante'
      fullPath: '/mi-restaurante'
      preLoaderRoute: typeof MiRestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupones': {
      id: '/cupones'
      path: '/cupones'
      fullPath: '/cupones'
      preLoaderRoute: typeof CuponesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente-dashboard': {
      id: '/cliente-dashboard'
      path: '/cliente-dashboard'
      fullPath: '/cliente-dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/': {
      id: '/restaurantes/'
      path: '/restaurantes'
      fullPath: '/restaurantes/'
      preLoaderRoute: typeof RestaurantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/$id': {
      id: '/restaurantes/$id'
      path: '/restaurantes/$id'
      fullPath: '/restaurantes/$id'
      preLoaderRoute: typeof RestaurantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidores/$id': {
      id: '/repartidores/$id'
      path: '/$id'
      fullPath: '/repartidores/$id'
      preLoaderRoute: typeof RepartidoresIdRouteImport
      parentRoute: typeof RepartidoresRoute
    }
    '/mi-restaurante/pedidos': {
      id: '/mi-restaurante/pedidos'
      path: '/pedidos'
      fullPath: '/mi-restaurante/pedidos'
      preLoaderRoute: typeof MiRestaurantePedidosRouteImport
      parentRoute: typeof MiRestauranteRoute
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/restaurantes/$id/panel': {
      id: '/restaurantes/$id/panel'
      path: '/panel'
      fullPath: '/restaurantes/$id/panel'
      preLoaderRoute: typeof RestaurantesIdPanelRouteImport
      parentRoute: typeof RestaurantesIdRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface MiRestauranteRouteChildren {
  MiRestaurantePedidosRoute: typeof MiRestaurantePedidosRoute
}

const MiRestauranteRouteChildren: MiRestauranteRouteChildren = {
  MiRestaurantePedidosRoute: MiRestaurantePedidosRoute,
}

const MiRestauranteRouteWithChildren = MiRestauranteRoute._addFileChildren(
  MiRestauranteRouteChildren,
)

interface RepartidoresRouteChildren {
  RepartidoresIdRoute: typeof RepartidoresIdRoute
}

const RepartidoresRouteChildren: RepartidoresRouteChildren = {
  RepartidoresIdRoute: RepartidoresIdRoute,
}

const RepartidoresRouteWithChildren = RepartidoresRoute._addFileChildren(
  RepartidoresRouteChildren,
)

interface RestaurantesIdRouteChildren {
  RestaurantesIdPanelRoute: typeof RestaurantesIdPanelRoute
}

const RestaurantesIdRouteChildren: RestaurantesIdRouteChildren = {
  RestaurantesIdPanelRoute: RestaurantesIdPanelRoute,
}

const RestaurantesIdRouteWithChildren = RestaurantesIdRoute._addFileChildren(
  RestaurantesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteDashboardRoute: ClienteDashboardRoute,
  ClientesRoute: ClientesRouteWithChildren,
  CuponesRoute: CuponesRoute,
  LoginRoute: LoginRoute,
  MiRestauranteRoute: MiRestauranteRouteWithChildren,
  MisEntregasRoute: MisEntregasRoute,
  MisPedidosRoute: MisPedidosRoute,
  NotificacionesRoute: NotificacionesRoute,
  NuevoPedidoRoute: NuevoPedidoRoute,
  PedidosRoute: PedidosRoute,
  RankingsRoute: RankingsRoute,
  RepartidorDashboardRoute: RepartidorDashboardRoute,
  RepartidoresRoute: RepartidoresRouteWithChildren,
  ReportesRoute: ReportesRoute,
  RestauranteDashboardRoute: RestauranteDashboardRoute,
  ZonasRoute: ZonasRoute,
  RestaurantesIdRoute: RestaurantesIdRouteWithChildren,
  RestaurantesIndexRoute: RestaurantesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
